apiVersion: kubermatic.k8c.io/v1
kind: KubermaticSetting
metadata:
  name: globalsettings
spec:
  cleanupOptions:
    enabled: true
  customLinks:
    - icon: ""
      label: Grafana (seed)
      location: default
      url: https://grafana.kkp.172.22.173.121.nip.io:8443
    - icon: ""
      label: Loki (seed)
      location: default
      url: https://grafana.kkp.172.22.173.121.nip.io:8443/explore
    - icon: ""
      label: Prometheus (seed)
      location: default
      url: https://prometheus.kkp.172.22.173.121.nip.io:8443
    - icon: ""
      label: Alertmanager (seed)
      location: default
      url: https://alertmanager.kkp.172.22.173.121.nip.io:8443
    - icon: ""
      label: Grafana (user clusters)
      location: default
      url: https://grafana-user.kkp.172.22.173.121.nip.io:8443
    - icon: ""
      label: Alertmanager (user clusters)
      location: default
      url: https://alertmanager-user.kkp.172.22.173.121.nip.io:8443
    - icon: ""
      label: Documentation
      location: default
      url: https://docs.kubermatic.com/kubermatic/main/
  defaultNodeCount: 1
  displayAPIDocs: true
  displayDemoInfo: true
  displayTermsOfService: false
  enableDashboard: true
  enableExternalClusterImport: true
  enableOIDCKubeconfig: false
  machineDeploymentVMResourceQuota:
    enableGPU: false
    maxCPU: 64
    maxRAM: 512
    minCPU: 1
    minRAM: 2
  mlaAlertmanagerPrefix: alertmanager-user
  mlaGrafanaPrefix: grafana-user
  restrictProjectCreation: false
  restrictProjectDeletion: false
  restrictProjectModification: false
  userProjectsLimit: 5
